language: node_js
node_js:
- 'stable'

cache: 'yarn'

script: npm run test:ci

before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
# Only the node version 6 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
